### ISSUE TITLE
config.dhall - remove poolActionsConfig

### ISSUE THREAD

**Issue by LucasRibeiroAlves** [spectrum-finance/cardano-dex-backend#73]
In the config.dhall file, there is a section `poolActionsConfig` that makes the bot fail to run.

I suggest to comment out or remove the entire section to prevent this problem, as it isn't necessary anymore and it's causing problems.

`  poolActionsConfig =
    { safeTxFeeLovalace = +300000
    },
`

**Comment by Bromel777** [comment]
removed in https://github.com/spectrum-finance/cardano-dex-backend/pull/74
